version: "3.8"

services:
  frontend:
    build: FE/.
    ports:
      - "8080:80"
    depends_on:
      - backend
      - ai
    networks: 
      - app-network
    restart: unless-stopped

  backend:
    build: BE/.
    ports:
      - "8000:8000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: hrd_db
    depends_on:
      mongo:
        condition: service_healthy
    networks: 
      - app-network
    restart: unless-stopped

  ai:
    build: AI/.
    ports:
      - "5050:5050"
    env_file:
      - AI/.env
    environment:
      BACKEND: backend
      BACKEND_PORT: 8000
    depends_on:
      - backend
    networks: 
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: